[project]
name = 'Decentralized-Digital-Identity-Credential-Verification'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.credential-schema]
path = 'contracts/credential-schema.clar'
clarity_version = 2
epoch = 2.5

[contracts.identity-provider]
path = 'contracts/identity-provider.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
